// <auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Cyviz.Infrastructure;

#nullable disable

namespace Cyviz.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("Cyviz.Domain.Device", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("Capabilities")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Firmware")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("LastSeenUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Protocol")
                    .HasColumnType("INTEGER");

                b.Property<byte[]>("RowVersion")
                    .HasColumnType("BLOB");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<int>("Type")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Status", "Type");

                b.ToTable("Devices");
            });

            modelBuilder.Entity("Cyviz.Domain.DeviceCommand", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("Command")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("IdempotencyKey")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long?>("LatencyMs")
                    .HasColumnType("INTEGER");

                b.Property<string>("Result")
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("DeviceId", "IdempotencyKey")
                    .IsUnique();

                b.ToTable("Commands");
            });

            modelBuilder.Entity("Cyviz.Domain.DeviceTelemetry", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("DeviceId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>(("Json"))
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("TimestampUtc")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("DeviceId", "TimestampUtc");

                b.ToTable("Telemetry");
            });
#pragma warning restore 612, 618
        }
    }
}
